name: rivu_v1
description: "Mobile application for Rivu"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    # State Management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

  # Bluetooth
  flutter_blue_classic: ^0.0.7

  # Session / Storage
  shared_preferences: ^2.2.3

  firebase_core: ^2.27.0 
  firebase_database: ^10.4.0 

  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  google_nav_bar: ^5.0.7
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  uuid: ^4.5.2
  flutter_expandable_fab: ^2.5.2
  elegant_nav_bar: ^0.0.22
  web_socket_channel: ^3.0.3
  weather_animation: ^1.1.2
  intl: ^0.20.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code Generators
  build_runner: ^2.4.10
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/images/
    - assets/icon/

flutter_native_splash:
  color: "#3AA346" 
  image: assets/images/logo.png
  android_gravity: center
  ios_content_mode: center
  web: false 
  android: true
  ios: true
